# Generated by Django 2.2.5 on 2020-01-23 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=120, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrudeFeedstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('specific_gravity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sulphur_level', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('kquery_curve_string', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefinedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('specific_gravity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('feedstock_indicator', models.BooleanField(default=False)),
                ('percent_output_by_mass', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefinedProductsWeightByMass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefineryProcessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit_type_code', models.CharField(blank=True, max_length=3, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_models.Country')),
            ],
        ),
        migrations.CreateModel(
            name='FeedstockProductSlateCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedstockproductslate_name', models.CharField(blank=True, max_length=120)),
                ('crude_feedstock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_models.CrudeFeedstock')),
                ('intermediate_feedstock_products', models.ManyToManyField(blank=True, null=True, related_name='intermediate_feedstock_products', to='core_models.RefinedProduct')),
                ('products', models.ManyToManyField(blank=True, to='core_models.RefinedProduct')),
                ('refinery_processing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_models.RefineryProcessUnit')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='country_region_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core_models.Region'),
        ),
    ]
