# Generated by Django 2.2.5 on 2020-01-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinedproduct',
            name='kquery_curve_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
